server:
  port: 8080
  session-timeout: 30
  tomcat.uri-encoding: UTF-8

# java config
datasource:
  master:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: rootyzf
      driver-class-name: com.mysql.jdbc.Driver
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  slave:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/test1?useUnicode=true&characterEncoding=utf8&useSSL=true
      username: root
      password: rootyzf
      driver-class-name: com.mysql.jdbc.Driver
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true



#boot just DI datasource
#sharding:
#  jdbc:
#    datasource:
#      names: ds_master,ds_slave
#      ds_master:
#        type: com.zaxxer.hikari.HikariDataSource
#        url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false
#        username: root
#        password: rootyzf
#        driver-class-name: com.mysql.jdbc.Driver
#        cachePrepStmts: true
#        prepStmtCacheSize: 250
#        prepStmtCacheSqlLimit: 2048
#        useServerPrepStmts: true
#      ds_slave:
#        type: com.zaxxer.hikari.HikariDataSource
#        url: jdbc:mysql://localhost:3307/test?useUnicode=true&characterEncoding=utf8&useSSL=true
#        username: root
#        password: rootyzf
#        driver-class-name: com.mysql.jdbc.Driver
#        cachePrepStmts: true
#        prepStmtCacheSize: 250
#        prepStmtCacheSqlLimit: 2048
#        useServerPrepStmts: true
#    config:
#      masterslave:
#        name: ds_ms
#        master-data-source-name: ds_master
#        slave-data-source-names: ds_slave
#